// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

DMibMemoryInterpose0(malloc_zone_t *, malloc_default_zone) 
DMibMemoryInterpose2(malloc_zone_t *, malloc_create_zone, vm_size_t _0, unsigned _1)
DMibMemoryInterpose1(void, malloc_destroy_zone, malloc_zone_t *_0)
DMibMemoryInterpose2(void *, malloc_zone_malloc, malloc_zone_t *_0, size_t _1)
DMibMemoryInterpose3(void *, malloc_zone_calloc, malloc_zone_t *_0, size_t _1, size_t _2)
DMibMemoryInterpose2(void *, malloc_zone_valloc, malloc_zone_t *_0, size_t _1)
DMibMemoryInterpose2(void, malloc_zone_free, malloc_zone_t *_0, void * _1)
DMibMemoryInterpose3(void *, malloc_zone_realloc, malloc_zone_t *_0, void * _1, size_t _2)
DMibMemoryInterpose1(malloc_zone_t *, malloc_zone_from_ptr, const void *_0)
DMibMemoryInterpose1(size_t, malloc_size, const void *_0)
DMibMemoryInterpose1(size_t, malloc_good_size, size_t _0)
DMibMemoryInterpose3(void *, malloc_zone_memalign, malloc_zone_t *_0, size_t _1, size_t _2)
DMibMemoryInterpose4(unsigned, malloc_zone_batch_malloc, malloc_zone_t *_0, size_t _1, void **_2, unsigned _3)
DMibMemoryInterpose3(void, malloc_zone_batch_free, malloc_zone_t *_0, void **_1, unsigned _2)
DMibMemoryInterpose0(malloc_zone_t *, malloc_default_purgeable_zone)
DMibMemoryInterpose1(void, malloc_make_purgeable, void *_0)
DMibMemoryInterpose1(int, malloc_make_nonpurgeable, void *_0)
DMibMemoryInterpose1(void, malloc_zone_register, malloc_zone_t *_0)
DMibMemoryInterpose1(void, malloc_zone_unregister, malloc_zone_t *_0)
DMibMemoryInterpose2(void, malloc_set_zone_name, malloc_zone_t *_0, const char *_1)
DMibMemoryInterpose1(const char *, malloc_get_zone_name, malloc_zone_t *_0)
DMibMemoryInterpose2(size_t, malloc_zone_pressure_relief, malloc_zone_t *_0, size_t _1)
DMibMemoryInterpose4(kern_return_t, malloc_get_all_zones, task_t _0, memory_reader_t _1, vm_address_t **_2, unsigned *_3)
DMibMemoryInterpose1(void, malloc_zone_print_ptr_info, void *_0)
DMibMemoryInterpose1(boolean_t, malloc_zone_check, malloc_zone_t *_0)
DMibMemoryInterpose2(void, malloc_zone_print, malloc_zone_t *_0, boolean_t _1)
DMibMemoryInterpose2(void, malloc_zone_statistics, malloc_zone_t *_0, malloc_statistics_t *_1)
DMibMemoryInterpose2(void, malloc_zone_log, malloc_zone_t *_0, void *_1)
//DMibMemoryInterpose0(struct mstats, mstats)
DMibMemoryInterpose1(boolean_t, malloc_zone_enable_discharge_checking, malloc_zone_t *_0)
DMibMemoryInterpose1(void, malloc_zone_disable_discharge_checking, malloc_zone_t *_0)
DMibMemoryInterpose2(void, malloc_zone_discharge, malloc_zone_t *_0, void * _1)
DMibMemoryInterpose2(void, malloc_zone_enumerate_discharged_pointers, malloc_zone_t *_0, void (^_1)(void *memory, void *info))

DMibMemoryInterpose1(void *, malloc, size_t _0)
DMibMemoryInterpose1(void *, valloc, size_t _0)
DMibMemoryInterpose2(void *, calloc, size_t _0, size_t _1)
DMibMemoryInterpose2(void *, realloc, void *_0, size_t _1)
DMibMemoryInterpose2(void *, reallocf, void *_0, size_t _1)
DMibMemoryInterpose1(void, free, void *_0)
DMibMemoryInterpose1(void, vfree, void *_0)
DMibMemoryInterpose3(int, posix_memalign, void **_0, size_t _1, size_t _2)
	
DMibMemoryInterpose1(int, malloc_jumpstart, int _0)

DMibMemoryInterpose1(void *, _Znwm, size_t _0)
DMibMemoryInterpose1(void *, _Znam, size_t _0)
DMibMemoryInterpose1(void , _ZdlPv, void * _0)
DMibMemoryInterpose1(void , _ZdaPv, void * _0)
DMibMemoryInterpose1(void *, _ZnwmRKSt9nothrow_t, size_t _0)
DMibMemoryInterpose1(void *, _ZnamRKSt9nothrow_t, size_t _0)
DMibMemoryInterpose1(void , _ZdaPvRKSt9nothrow_t, void *_0)
DMibMemoryInterpose1(void , _ZdlPvRKSt9nothrow_t, void *_0)
